import { Document, Page, StyleSheet, Text, View } from '@react-pdf/renderer';
import { Student } from '@/lib/types';

const styles = StyleSheet.create({
  page: {
    padding: 32,
    fontSize: 12,
    fontFamily: 'Helvetica',
  },
  header: {
    fontSize: 18,
    marginBottom: 12,
    textAlign: 'center',
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  table: {
    marginTop: 12,
    borderTop: '1 solid #999',
    borderBottom: '1 solid #999',
  },
  tableRow: {
    flexDirection: 'row',
    borderBottom: '1 solid #eee',
  },
  th: {
    fontWeight: 'bold',
    padding: 6,
    width: '33.33%'
  },
  td: {
    padding: 6,
    width: '33.33%'
  },
  footer: {
    marginTop: 16,
    fontSize: 10,
    textAlign: 'right',
  }
});

export function Marksheet({ student }: { student: Student }) {
  const subjects = Object.keys(student.marks);
  const total = subjects.reduce((acc, s) => acc + (student.marks[s] || 0), 0);
  const percentage = Math.round((total / (subjects.length * 100)) * 100);
  const grade = percentage >= 90 ? 'A+' : percentage >= 80 ? 'A' : percentage >= 70 ? 'B' : percentage >= 60 ? 'C' : 'D';

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.header}>ReportConnect - Report Card</Text>

        <View style={styles.row}>
          <Text>Student: {student.studentName} ({student.studentId})</Text>
          <Text>Class: {student.class}-{student.section}</Text>
        </View>
        <View style={styles.row}>
          <Text>Parent Email: {student.parentEmail}</Text>
          <Text>Date: {new Date().toLocaleDateString()}</Text>
        </View>

        <View style={styles.table}>
          <View style={styles.tableRow}>
            <Text style={styles.th}>Subject</Text>
            <Text style={styles.th}>Marks</Text>
            <Text style={styles.th}>Remarks</Text>
          </View>
          {subjects.map((sub) => (
            <View key={sub} style={styles.tableRow}>
              <Text style={styles.td}>{sub}</Text>
              <Text style={styles.td}>{student.marks[sub]}</Text>
              <Text style={styles.td}>{student.marks[sub] >= 75 ? 'Good' : student.marks[sub] >= 60 ? 'Satisfactory' : 'Needs Improvement'}</Text>
            </View>
          ))}
        </View>

        <View style={{ marginTop: 12 }}>
          <Text>Total: {total} / {subjects.length * 100}</Text>
          <Text>Percentage: {percentage}%</Text>
          <Text>Grade: {grade}</Text>
        </View>

        <Text style={styles.footer}>Generated by ReportConnect</Text>
      </Page>
    </Document>
  );
}
